name: Update and Build examples on release

on:
  workflow_dispatch: 
  release:
    types: [published]
  [push]
jobs:
  demo:
    strategy:
      matrix:
        node: ["20.x"]
        os: [ubuntu-latest]
        demo: [react-app, next-app, angular-app, firebase-next-app, firebase-react-app, whitelabel-app, starkex-react-app]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - uses: listendev/action@v0.12
        with:
          jwt: ${{ secrets.LSTN }}
          ci: only
      - name: Build ${{ matrix.demo }} demo
        run: |
          npm i -g npm-check-updates
          cd demo/${{ matrix.demo }}
          ncu -u --target=minor
          ncu -u "/^@web3auth.*$/"
          npm install
          npm run build
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          push: origin HEAD:master
          author_name: Torus Bot
          author_email: no-reply@tor.us
          default_author: user_info

          # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
          # - ignore -> errors will be logged but the step won't fail
          # - exitImmediately -> the action will stop right away, and the step will fail
          # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
          # Default: ignore
          pathspec_error_handling: exitImmediately
